[tool.poetry]
name = "schema-validator"
version = "0.1.0"
description = "Small library for validating file schema"
authors = ["Krzysztof Ignasiak <kignasiak01@gmail.com>"]


[tool.poetry.dependencies]
python = "3.10"
pydantic = "1.8.1" 


[tool.poetry.dev-dependencies]
pytest = "^6.2"
